import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { MainContainer } from "@/components/containers/main-container";
import { Header } from "@/components/header/header";
import NextTopLoader from 'nextjs-toploader';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "syepost",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} relative scroll pb-5 overflow-x-hidden dark`}>
      <Header />
      <NextTopLoader />
        {children}
      </body>
    </html>
  );
}
