import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Container } from "@/components/container/container";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "syepost",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} dark relative`}>
        <Container>
          {children}
        </Container>
      </body>
    </html>
  );
}
